package tracing_session

/*
#include "session.h"
*/
import "C"

// TODO: options, types

// TODO: GO-style names for flags with appropriate description?
const (
	EVENT_ENABLE_PROPERTY_SID               = 0x001
	EVENT_ENABLE_PROPERTY_TS_ID             = 0x002
	EVENT_ENABLE_PROPERTY_STACK_TRACE       = 0x004
	EVENT_ENABLE_PROPERTY_PSM_KEY           = 0x008
	EVENT_ENABLE_PROPERTY_IGNORE_KEYWORD_0  = 0x010
	EVENT_ENABLE_PROPERTY_PROVIDER_GROUP    = 0x020
	EVENT_ENABLE_PROPERTY_ENABLE_KEYWORD_0  = 0x040
	EVENT_ENABLE_PROPERTY_PROCESS_START_KEY = 0x080
	EVENT_ENABLE_PROPERTY_EVENT_KEY         = 0x100
	EVENT_ENABLE_PROPERTY_EXCLUDE_INPRIVATE = 0x200
)

const (
	TRACE_LEVEL_VERBOSE = 5
)
